export const ACHIEVEMENT_ID = {
  firstCampaignWin: 1,
  tenCampaignWins: 2,
  hundredCampaignWins: 3,
  fiveHundredCampaignWins: 4,
  maxThreeWarriorsCampaignWin: 5,
  maxTwoWarriorsCampaignWin: 6,
  maxOneWarriorCampaignWin: 7,
  peasantsOnlyCampaignWin: 8,
  undefeatedCampaignWin: 9,
  goldHoarderCampaignWin: 10,
  goldSaverCampaignWin: 11,
  holyOrderCampaignWin: 12,
  arcaneCircleCampaignWin: 13,
  diverseCompanyCampaignWin: 14,
  ismoCampaignWin: 15,
  arcaneMysteriesCampaignWin: 16,
  ghostWarriorRecruit: 17,
  humanOnlyCampaignWin: 18,
  elfOnlyCampaignWin: 19,
  dwarfOnlyCampaignWin: 20,
  orcOnlyCampaignWin: 21,
  shiningWarriorRecruit: 22,
  actionDamage10: 23,
  actionDamage15: 24,
  actionDamage20: 25,
  actionDamage25: 26,
  actionHealing10: 27,
  actionHealing15: 28,
  actionHealing20: 29,
} as const;

export type AchievementId =
  (typeof ACHIEVEMENT_ID)[keyof typeof ACHIEVEMENT_ID];
